name: Build And Release

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Prepare
        run: |
          sudo apt update
          sudo apt install -y llvm-19 llvm-19-dev clang-19 libc++-19-dev ninja-build python3 git patch libglib2.0-dev
          ./prepare.sh

      - name: Build
        run: |
          cd v8/out
          ninja senkora_v8
          
      - name: install
        run: |
          ./install.sh
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: v8-linux-x86_64
          path: |
            miniroot/include/
            miniroot/lib/

  release:
    needs: [linux]
    runs-on: ubuntu-latest
    name: Release built binaries
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Merge Artifacts
        run: |
          sudo apt install -y zip
          for dir in v8-*-x86_64; do
            zip -r $dir.zip $dir
          done

      - name: Upload Artifacts
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          prerelease: false
          files: |
            v8-*-x86_64.zip
